### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by julen** [evernote/zing#377]
Let's make sure zing runs on Python 3. This will also eventually drop support for Python 2 because some dependencies with support for security fixes, namely Django, only run on Python 3.

- [x] Upgrade to py2- & py3-compatible dependencies as much as possible (#378)
- [x] Make sure tests run on py3
- [x] Update code to py3 (https://docs.python.org/3/howto/pyporting.html)
- [x] Drop Python 2 support
- [x] Upgrade to Django 2 (#399)
- [x] Upgrade to Django 3 (#400)
- [x] Upgrade library dependencies to their latest versions

**Comment by julen** [comment]
Closing since the gross of the migration has been done, the rest will be ad-hoc follow-up fixes.
