### ISSUE TITLE
Upgrade dependencies to py3-compatible versions

### ISSUE THREAD

**Issue by julen** [evernote/zing#378]
Let's upgrade our direct library dependencies to their latest versions supporting both py2 and py3. With this we'll be able to later on switch our testing matrix to run on py3.

Here's the list of all our current direct dependencies, with the specific versions we can upgrade to:

# Django and apps

- [x] Django==1.11.18 (1.11.26 is the last released version supporting both py2 and py3)

- [x] django-allauth==0.30.0 (0.40 is the last released version supporting both py2 and py3)
- [x] django-assets==0.12 (latest version already, supports both py2 and py3)
- [x] django-contact-form==1.4.2 (1.7 is the last released version supporting both py2 and py3)
- [x] django-contrib-comments==1.8.0 (1.9.1 is the last released version supporting both py2 and py3)
- [x] django-redis==4.9.1 (4.10.0 is the last released version supporting both py2 and py3)
- [x] django-rq==1.0.0 (2.1.0 is the last released version supporting both py2 and py3)
- [x] django-statici18n==1.5.0 (1.8.3 is the last released version supporting both py2 and py3)

# Libraries
- [x] ~~cssmin==0.2.0 (dependency of django-assets, no longer maintained)~~
- [x] elasticsearch>=1.0.0,<2.0.0  (the library already supports py2+py3, the version to use depends on the runtime. See #350 for further details)
- [x] lxml==4.2.1 (4.4.2 is the last released version supporting both py2 and py3)
- [x] python-dateutil==2.5.3 (2.8.1 is the last released version supporting both py2 and py3)
- [x] python-levenshtein==0.12.0 (latest version already, supports both py2 and py3)
- [x] rq==0.7.1 (1.1.0 is the last released version supporting both py2 and py3)

# Translate Toolkit
- [x] translate-toolkit==2.2.5 (2.4.0 is the last released version supporting both py2 and py3)

# Database
- [x] mysqlclient>=1.3.3 (1.4.6 is the last released version supporting both py2 and py3)
- [x] psycopg2>=2.4.5 (2.8.4 is the last released version supporting both py2 and py3)

# Logging
- [x] raven==6.5.0 (to be upgraded/replaced by sentry-python)

# Testing
- [x] factory_boy==2.8.1 (2.12.0 is the last released version supporting both py2 and py3)
- [x] fakeredis==0.8.1 (1.1.0 is the last released version supporting both py2 and py3)
- [x] pytest==3.0.2  (4.6 is the last series supporting py2 and py3, https://docs.pytest.org/en/latest/py27-py34-deprecation.html)
- [x] ~~pytest-catchlog==1.2.2 (latest version already, supports both py2 and py3)~~ (this is now part of pytest)
- [x] pytest-cov==2.3.1 (2.8.1 is the last released version supporting both py2 and py3)
- [x] pytest-django==3.1.2 (3.7.0 is the last released version supporting both py2 and py3)

# Linting
- [x] ~flake8==3.4.1~ will be replaced by python-black in #392
- [x] isort>=4.2.15 (4.3.21 is the last released version supporting both py2 and py3)
- [x] ~pycodestyle==2.3.1~ will be replaced by python-black in #392
- [x] ~pydocstyle==1.0.0~ will be replaced by python-black in #392
- [x] pylint==1.7.2 (1.9.5 is the last released version supporting both py2 and py3)
